bellshade/Python

- CONTRIBUTING.md
meperbaiki kekurangan kata dan memperbaiki dokumentasi
saya menggunakan (im used):
- ``os`` = ``macOS``
- ``python`` = ``python3 3.9.0``
testing tidak termasuk, hanya memperbaiki  markdown file
> docs: memperbaiki contributing

- chiper/README.md
test automerge dengan label
saya menggunakan (im used):
- ``python`` = ``python3 --version``
> Update README.md not merge

- conversion/binary_to_octal.py
menambahkan konversi bilangan binary ke bilangan oktal
saya menggunakan (im used):
- ``os`` = ``macOS``
- ``python`` = ``python3 3.9.0``
> add: menambahkan konversi bilangan binary ke oktal

- genetic_algo/basic_string.py
Menambahkan dokumentasi berupa komentar pada kode untuk memberikan penjelasan yang lebih pada kode
saya menggunakan (im used):
- ``os`` = ``macOS``
- ``python`` = ``python3 3.9.0``
tidak ada perubahan pada koding, hanya memberikan komentar untuk memperjelas kode
**python maintainer**
@slowy07
**maintainer dokumentasi**
@dydrmr5
@nomadkode
> docs: menambahkan komentar penjelasan pada kode

- conversion/binary_to_string.py
Tipe error saat tipe input tidak sesuai dengan yang diharapkan adalah `TypeError`. `ValueError` untuk input dengan nilai yang salah. Dikutip dari dokumentasi Python:
> Passing arguments of the wrong type (e.g. passing a list when an int is expected) should result in a TypeError, but passing arguments with the wrong value (e.g. a number outside expected boundaries) should result in a ValueError.
Dikutip dari [PEP-8](https://www.python.org/dev/peps/pep-0008/#programming-recommendations):
> Object type comparisons should always use isinstance() instead of comparing types directly:
> For sequences, (strings, lists, tuples), use the fact that empty sequences are false: `if not seq:`
saya menggunakan (I used):
- ``python`` = ``Python 3.9.6``
> Perubahan Konversi Binary ke String

- .flake8
- .github/workflows/pythonapp.yml
- CONTRIBUTING.md
Gunakan config sebagai ganti flags dan options.
> Tambahkan Config untuk flake8

- searching/_types.py
- searching/binary_search.py
- searching/linear_search.py
- ``python`` = ``CPython 3.9.6``
Closes #18
> Implement searching algorithms

- Basic/Operator.py
- [] pytest
**Python Maintainer**:
@norinorin
@athallahmaajid
@KelvinMulyawan
@slowy07
**Docs maintainer**:
@dydrmr5
@nomadkode
> add: Operator

- Basic/tipe_data/tipe_data.py
tipe data yang terdapat pada python
- ``os`` = ``macOS``
- ``python`` = ``python3.9``
linked issue #33
> add: tipe_data python

- sorting/pop_sort.py
Saya menambahkan salah satu contoh logika sorting yaitu pop_sort
- ``os`` = ``GNU/Linux Manjaro 21.1.4 Pahvo``
- ``python`` = ``Python 3.9.7``
> Menambahkan sorting/pop_sort

- Basic/class/README.md
- Basic/class/class.py
- Basic/class/const_desct.py
- Basic/class/methods.py
- README.md
- sorting/pop_sort.py
- ``python`` = ``Python 3.8.6``
linked issue #34
> Adding Basic: Class

- Basic/tipe_data/README.md
Sedikit memperbaiki typo dan menambahkan tipe data set dan frozenset
linked issue #33
> docs: Menambahkan tipe data set and frozenset

- DIRECTORY.md
- math/sigmoid.py
- ``python`` = ``py 3.9``
linked issue #120
> add : sigmoid

- DIRECTORY.md
- other/power_dac.py
Menambah script untuk menghitung pangkat ``a^n`` menggunakan metode divide and conquer
- ``python`` = ``3.9.5``
linked issue #109
> feat: tambah script untuk menghitung pangkat

- Basic/README.md
- Basic/python_math/README.md
- Basic/python_math/math_eksponen_logaritma.py
- Basic/python_math/math_konstanta.py
- Basic/python_math/math_konversi_sudut.py
- Basic/python_math/math_pembulatan.py
- Basic/python_math/math_trigonometri.py
- DIRECTORY.md
Menambahkan materi tentang penggunaan standard library `math`
linked issue #124
> add: standard library math

- DIRECTORY.md
- math/digit_sum.py
Menambahkan algoritma digit sum, beserta penjelasan singkat bagaimana cara kerja algoritma tersebut
- ``python`` = ``3.9.5`
linked issue #125
> feat: tambah algoritma digit sum

- DIRECTORY.md
- math/radian.py
Tambah script untuk menghitung radian, derajat, dan gradian.
NB : Sejauh ini, saya tidak menemukan kemungkinan input fungsi yang tidak valid, jadi pada script ini tidak saya tambah fungsionalitas untuk me-raise exception
- ``python`` = ``3.9.5``
linked issue #136
> feat: tambah script untuk menghitung radian

- DIRECTORY.md
- math/recursion_power.py
- ``python`` = ``Python 3.9.7``
linked issue #135
> feat: pangkat dengan rekursif

- math/is_prime.py
* Saya memindahkan file `/other/isPrime.py` ke `/math/is_prime.py'
* Saya melakukan optimisasi algoritma `is_prime.py`
* Saya menambahkan docstring dan doctest untuk `is_prime.py`
- ``python`` = ``Python 3.9.7``
> fix: optimisasi dan penambahan docstring ke isPrime.py

- DIRECTORY.md
- struktur_data/singly_linked_list.py
Menambahkan script untuk singly linked list disertai penjelasan tentang class dan method yang digunakan
NB : Silakan untuk mengedit dan menambah markdown pada file ini, ada beberapa method yang belum
saya implementasikan dan saya rasa method-method yang belum diimplementasikan dapat dikerjakan oleh
kontributor di masa depan
- ``python`` = ``3.9.8``
linked issue #146
> feat: tambah script untuk singly linked list

- web_programming/PaginationHelper.py
Saya menambahkan helper class `PaginationHelper.py` untuk membantu dalam proses pagination yang biasa dilakukan dalam pengembangan web.
> add: menambahkan `PaginationHelper.py`

- web_programming/breadcrumb_generator.py
Menambahkan algoritma `breadcrumb_generator.py` untuk menghasilkan navigasi breadcrumb yang sering dipakai dalam pembangunan web.
> add: menambahkan `breadcrumb_generator.py`

- other/rgb_to_hex.py
Menambahkan algoritma yang dapat mengonversikan value RGB ke hex.
> add: menambahkan `rgb_to_hex.py`

- other/is_palindrom.py
Saya melakukan beberapa perbaikan terhadap algoritma `Palindrom.py` yang sudah ada.
* Melakukan rename file.
* Mengubah algoritma.
* Menambahkan docstring dan doctest.
> feat: memperbaiki `Palindrom.py` 

- Basic/04_operator/README.md
- Basic/16_class/README.md
- Basic/17_inheritance/README.md
- object_oriented_programming/README.md
Menambahkan link yang langsung terhubung ke tutorial video kelas terbuka. Link yang ditambahkan diantaranya :
1. Operator
2. Object Oriented Programming
- ``python`` = ``3.9.8``
linked issue #161
> add: tambah embed link kelas terbuka di markdown

- other/hex_to_rgb.py
Saya menambahkan algoritma `hex_to_rgb.py` untuk membantu konversi kode warna hex menjadi rgb.
> add: menambahkan `hex_to_rgb.py`

- web_programming/get_random_quote.py
Menambahkan fungsi sederhana yang memanggil API Quotable untuk mendapatkan quote secara random.
> add: menambahkan `get_random_quote.py`

- DIRECTORY.md
- object_oriented_programming/intermediate/inheritance/README.md
- object_oriented_programming/intermediate/inheritance/inheritance.py
- ``python`` = ``python 3.9.9``
linked issue #172
> Inheritance

- struktur_data/binary_search_tree.py
Tambah algoritma binary search tree. Kode saat ini hanya memuat method insert dan traversal (preorder, inorder, dan postorder)
- ``os`` = ``lwindows 10``
- ``python`` = ``3.9.8``
linked issue #176
> feat: tambah algoritma binary search tree

- DIRECTORY.md
- math/prime_number_library.py
- ``python`` = ``Python 3.7.6``
linked issue #188
> feat: fungsi untuk menangani bilangan prima

- algorithm/arithmetic_analysis/rootsearch.py
menambahkan algoritma baru pada materi analisis numerik yaitu incremental root search. Incremental root search adalah algoritma untuk mencari nilai akar pada sebuah persamaan non linear satu variabel jika diberikan interval.
- ``os`` = ``EndeavourOS``
- ``python`` = ``python 3.8.8``
> feat: menambahkan algoritma incremental_root_search

- math/iteration_power.py
Menambahkan algoritma untuk perpangkatan menggunakan metode iteratif atau perulangan
- ``python`` = ``python3 -V 3.8.2``
linked issue #195
> feat: menambahkan iteration power, atau perpangkatan menggunakan metode perulangan

- DIRECTORY.md
- algorithm/sorting/bubble_sort_ascii.py
Menambahkan algoritma bubble sort untuk data string dan/atau angka dengan mengikuti urutan pada ASCII.
Jika data merupakan string, dan huruf pertama data 1 lebih besar (sesuai urutan ASCII) dari data 2, maka akan ditukar posisinya
- ``os`` = `` windows``
- ``python`` = ``python3 -V 3.8.2``
linked issue #196
> feat: menambahkan algoritma bubble sort string ascii

- Basic/01_introduction/README.md
> docs: Penambahan Action Table of Content dan perbaikan penulisan

- CODE_OF_CONDUCT.md
Menambahkan file code of conduct untuk melengkapi standar komunitas yang direkomendasikan dan mendorong kontribusi yang sehat dan membangun komunitas.
linked issue #204
> docs: penambahan file code of conduct

- Basic/01_introduction/README.md
- Basic/02_tipe_data/README.md
- Basic/02_tipe_data/tipe_data.py
> docs: Penambahan Table of Content ,perbaikan penulisan dan menambahkan kode pada file tipe data

- Basic/02_tipe_data/README.md
- Basic/02_tipe_data/tipe_data.py
- Basic/03_variable/README.md
- Basic/03_variable/string_variable.py
- Basic/03_variable/variable.py
- Basic/04_operator/README.md
- Menambahkan keterangan 
- Memperbaiki tabel
- ``python`` = ``python 3.9.7``
> docs: Merevisi README materi ke 4 

- README.md
Mengganti base url untuk visitor badge karena error
- ``os`` = ``Android``
> docs: memperbaiki visitor badge

- Basic/01_introduction/README.md
- Basic/02_tipe_data/README.md
- Basic/03_variable/README.md
- Basic/04_operator/README.md
- Basic/05_string/README.md
- Basic/05_string/string_python.py
- Meningkatkan pengalaman baca dokumentasi dengan penambahan keterangan pada tombol next | previous
- Menambahkan table of content pada materi string
- Menyamakan coding antara README dan praktikum pada materi string
- ``python`` = ``python 3.9.7``
> docs: memperbaiki readme materi string

- algorithm/networking_flow/ford_fulkerson.py
menambahkan informasi tentang ford fulkerson algorithm
testing precommit
- ``python`` = ``python3 3.10.8``
> fix: merubah nama fungsi pada BFS

- DIRECTORY.md
- struktur_data/tree/binary_tree_mirror.py
merubah binary tre ke mode binary tree secara refeleksi ( seperti cermin )
- ``python`` = ``python3 3.10.8``
linked issue: #224
> feat: menambahkan fungsi dari binary tree mirror

- DIRECTORY.md
- algorithm/backtracking/cari_kata.py
menambahkan solusi dari problem [word search](https://leetcode.com/problems/word-search/) dengan metode backtracking
- ``python`` = ``python3 3.10.9``
> Menambahkan solusi dari problem ``Cari kata``

- CONTRIBUTING.md
- README.md
saya memperbaiki dokumentasi dengan menambahkan link discord kelas terbuka
> docs: memperbaiki dokumentasi

- math/variance.py
> penambahan fungsi variance

- math/fibonacci.py
> add: menambahkan algoritma baru

- Basic/25_list_and_dict_comprehension/list_comprehension.py
Menambahkan kode untuk List Comprehension menggunakan contoh nested list atau perulangan bercabang.
- ``python`` = ``3.8.10``
linked issue #239
> feat: menambahkan list comprehension

- .pre-commit-config.yaml
menambahkan konfigurasi auto walrus pada pre-commit
- ``python`` = ``python3 3.10.9``
> feat: menambahkan konfigurasi auto walrus

- math/r2_score.py
> feat: menambahkan algoritma baru r2_score

- DIRECTORY.md
- implementation/audio_filter/audio_response.py
menambahakn contoh algoritma response audio
- ``python`` = ``python3 3.10.8``
> Audio response

- implementation/statistic/median.py
- implementation/statistic/modus.py
- implementation/statistic/rata_rata.py
- implementation/statistic/standard_deviasi.py
> feat:Menambahkan algoritma mean,media,modus

- implementation/statistic/entropy.py
- implementation/statistic/information_gain.py
- implementation/statistic/variance.py
> feat: menambahkan algoritma variance,entropy dan information gain

- DIRECTORY.md
- implementation/artificial_intelligence/k_means_clutser.py
- requirements.txt
kmeans aadalah algoritma yang melatih model yang mengelompokkan object serupa bersama-sama. algoritma menyelesaikan ini dengan memetakan setiap pengamatan dalam kumpulan data input ke titik di ruang n dimensi.
- ``python`` = ``3.10.9``
linked issue #246
> Kmeans clutser

- DIRECTORY.md
- implementation/artificial_intelligence/logistic_regression.py
regresi logistik, dalam statistika digunakan untuk prediksi probabilitas kejadian suatu peristiwa dengan mencocokkan data pada fungsi logit kurva logistik. Metode ini merupakan model linier umum yang digunakan untuk regresi binomial.
referensi:
- [medium](https://vincentmichael089.medium.com/machine-learning-2-logistic-regression-96b3d4e7b603)
- [wikipedia](https://id.wikipedia.org/wiki/Regresi_logistik)
- ``python`` = ``3.10.10``
linked issue #246
> feat: menambahkan fungsi logistik regressi

- DIRECTORY.md
- implementation/artificial_intelligence/k_nearest_neighbour.py
algoritma K-Nearest Neighbor (KNN) merupakan algoritma machine learning sederhana dan mudah diterapkan yang dapat digunakan untuk menyelesaikan masalah klasifikasi dan regresi. algoritma ini termasuk dalam jenis supervised learning. algoritma K-Nearest Neighbor (KNN) adalah algoritma machine learning yang bersifat non-parametric dan lazy learning. Metode yang bersifat non-parametric memiliki makna bahwa metode tersebut tidak membuat asumsi apa pun tentang distribusi data yang mendasarinya. Dengan kata lain, tidak ada jumlah parameter atau estimasi parameter yang tetap dalam model, terlepas data tersebut berukuran kecil ataupun besar.
- ``python`` = ``3.10.10``
linked issue #246
> K nearest neighbour

- implementation/statistic/multivariate_normal.py
> feat: menambahkan distribusi multivariate

- implementation/statistic/LabelEncoding.py
- implementation/statistic/softmax.py
> feat: menambahkan fungsi softmax dan class LabelEncoding

- implementation/statistic/factorAnalitic.py
> add: Menambahkan algorithm Factorial Analitic

- implementation/artificial_intelligence/fungsi_skoring.py
> feat: penambahan mean absolute percentage error dan update dokumentasi

- implementation/artificial_intelligence/normalization_data_tranform.py
> feat: menambahkan algoritma normalisasi

- math/counter.py
> feat: menambahkan algoritm counter(yaudah)

- math/persamaan_kuadarat_bilangan_kompleks.py
> fix: update logika baru

- math/random_generator.py
> feat: menambahkan algorith random

- Basic/26_dekorator/README.md
- Basic/26_dekorator/dekorator.py
- Basic/README.md
- DIRECTORY.md
> feat: menambahkan materi tentang dekorator

- DIRECTORY.md
- algorithm/sorting/quick_sorting.py
Menambahkan algoritma quick sorting
- ``python`` = `3.11.3`
linked issue #213
> feat: menambahkan algoritma quick sort

- math/sin.py
algoritma sinus merupakan algoritma tentang pembuatan sinus dengan series taylor tersebut merupakan hyperbolic algoritma pada putaran lingkaran tersebut
[!youtube](https://www.youtube.com/watch?v=cWBroMOwLFo&t=243s) [!pdf](https://people.math.sc.edu/girardi/m142/handouts/10sTaylorPolySeries.pdf)
> feat: menambah algoritma sinus

- DIRECTORY.md
- implementation/artificial_intelligence/similarity_searching.py
similarity search adalah kemiripan adalah teknik pembelajaran mesin yang digunakan untuk menemukan dokumen, gambar, atau data lainnya yang mirip dengan kueri yang diberikan
- ``python`` = ``3.11.3``
> feat: menambahkan algoritma similarity_search

- DIRECTORY.md
- algorithm/sorting/merge_sort.py
#295 
- ``python`` = ``3.11.3``
> Merge sort

- math/exponential_function.py
``Deskripsi``
Exponent merupakan fungsi matematika yang pangkat nya berbasis nilai eular
``Refence``
[wikipedia](https://en.wikipedia.org/wiki/Exponential_function)
- ``os`` = ``linux (Ubuntu 22.10)``
> feat: menambah exponential

- DIRECTORY.md
- algorithm/sorting/bitonic_sorting.py
Bitonic sorting adalah salah satu algoritma pengurutan (sorting algorithm) yang digunakan untuk mengurutkan suatu rangkaian (array) elemen. Algoritma ini memiliki ciri khas dalam pengurutan, yaitu urutan data yang diurutkan harus menjadi "bitonic" sebelum proses pengurutan dimulai. Urutan bitonic adalah sebuah urutan yang pertama secara terurut meningkat lalu secara terurut menurun, atau sebaliknya.
- ``python`` = ``3.11.4``
> chore: menambahkan bitonic sorting

- implementation/artificial_intelligence/linear_regression.py
- implementation/artificial_intelligence/logistic_regression.py
- implementation/artificial_intelligence/random_forest.py
perbaiki ini meliputkan berupa dokumentasi,kesalahan pemanggilan pakage typo dalam penulisan variabel pada kode tersebut
> fix: memperbaiki algoritma pada folder AI

- DIRECTORY.md
- algorithm/sorting/bogo_sorting.py
bogo sorting adalah algoritma yang sangat tidak efisien karena memiliki kompleksitas waktu O(∞). artinya, algoritma ini dapat membutuhkan waktu yang tidak terbatas untuk mengurutkan array. selain itu, algoritma ini juga memiliki kompleksitas ruang O(1). artinya, algoritma ini hanya menggunakan ruang memori yang konstan untuk mengurutkan array.
- ``python`` = ``3.11.5``
> chore: menambahkan bogo sorting

- math/convolution.py
description:
algoritm ini merupakan implementasi dari rumus sederhana dari convolution tersebut
- ``os`` = ``windows ``
- ``python`` = ``py -3 -V (Python 3.12) ``
> feat: adding algoritm simple convolution

- Basic/01_introduction/README.md
- Basic/02_tipe_data/README.md
Mengubah beberapa kalimat di markdown introduction dan tipe data dikarenakan typo. Tidak menggunakan/membuat Issue dikarenakan tidak ada penambahan dari sisi logic, hanya markdown untuk mengubah beberapa kata
> docs(basic): fix some typo in 01_introduction and 02_tipe_data
